config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  resources :events

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'pending' => 'orders#pending'

  get 'overview' => 'orders#overview'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get 'users/edit'

  get 'orders/index'

  get 'orders/new'

  get 'orders/edit'

  get 'orders/show'

  get 'orders/accept'

  get 'orders/decline'

  get 'searches/index'

  get 'searches/ask'

  get 'searches/result'

  get 'courses/index'

  get 'courses/edit'

  get 'courses/new'

  get 'courses/show'

  get 'menus/index'

  get 'menus/edit'

  get 'menus/new'

  get 'menus/show'

  get 'menu/index'

  get 'menu/new'

  get 'menu/edit'

  get 'menu/shot'

  get 'chefs/new'

  get 'welcome/index'

  get 'welcome/admin'

  get 'landing', to: 'events#landing'

  get 'cheflanding', to: 'events#cheflanding'

  resources :chefs do
    resources :menus do
      resources :courses
    end
  end

  resources :searches

  resources :orders

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :charges

  resources :subscribers

  root 'searches#ask'

  scope "(:locale)", locale: /en|es/ do
    resources :chefs
    resources :orders
    resources :searches
    resources :events
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :chef
  has_many :courses, dependent: :destroy

  mount_uploader :photo1, ChefPictureUploader
  mount_uploader :photo2, ChefPictureUploader
  mount_uploader :photo3, ChefPictureUploader
  mount_uploader :photo4, ChefPictureUploader
  mount_uploader :photo5, ChefPictureUploader

  validates :name, presence: true
  validates :price, presence: true

  def create
    menu = Menu.new(menu_params)

    menu.save
    redirect_to @menu
  end

  private
  def menu_params
    params.require(:menu).permit(
        :name, :price, :chef_id,
        :currency,
    :description,
    :cuisine_italian,
    :cuisine_peruvian,
    :cuisine_mediterranean,
    :cuisine_spanish,
    :cuisine_american,
    :cuisine_japanese,
    :cuisine_fusion,
    :cuisine_thai,
    :cuisine_vietnamese,
    :cuisine_latinamerican,
    :cuisine_indian,
    :cuisine_persian,
    :cuisine_bbq,
    :cuisine_argentinian,
    :cuisine_anticuchos,
    :cuisine_patisserie,
    :cuisine_exotic,
    :cuisine_german,
    :cuisine_brazilian,
    :option_alcohol,
    :option_change,
    :hashtags,
    :partysize,
    :photo1,
    :photo2,
    :photo3,
    :photo4,
    :photo5
    )
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "borussia", only: :index
  layout "admin", except: [:show]

  def index
    @chef = Chef.find(params[:chef_id])
    @menus = @chef.menus.all
  end

  def new
    @menu = Menu.new
    @chef = Chef.find(params[:chef_id])
    #@chef = Chef.find_by_email(current_user.email)
    #Change back when chefs edit themselves!
  end

  def edit
    @chef = Chef.find(params[:chef_id])
    @menu = @chef.menus.find(params[:id])
  end

  def update
    @chef = Chef.find(params[:chef_id])
    @menu = @chef.menus.find(params[:id])

    if @menu.update(menu_params)
      redirect_to chef_menus_url
    else
      render 'new'
    end
  end

  def create
    @chef = Chef.find(params[:chef_id])
    @menu = @chef.menus.create(menu_params)

    if @menu.save
      redirect_to chef_menus_url
    else
      render 'new'
    end
  end

  def show
    @menu = Menu.find(params[:id])
    @chef = Chef.find(params[:chef_id])
  end

  def destroy
    @chef = Chef.find(params[:chef_id])
    @menu = @chef.menus.find(params[:id])
    @menu.destroy

    redirect_to chef_menus_path(@chef)
  end

  private
  def menu_params
    params.require(:menu).permit(
        :name, :price, :chef_id,
        :currency,
        :description,
        :cuisine_italian,
        :cuisine_peruvian,
        :cuisine_mediterranean,
        :cuisine_spanish,
        :cuisine_american,
        :cuisine_japanese,
        :cuisine_fusion,
        :cuisine_thai,
        :cuisine_vietnamese,
        :cuisine_latinamerican,
        :cuisine_indian,
        :cuisine_persian,
        :cuisine_bbq,
        :cuisine_argentinian,
        :cuisine_anticuchos,
        :cuisine_patisserie,
        :cuisine_exotic,
        :cuisine_german,
        :cuisine_brazilian,
        :option_alcohol,
        :option_change,
        :hashtags,
        :partysize,
        :photo1,
        :photo2,
        :photo3,
        :photo4,
        :photo5,
        :eventtype
    )
  end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/edit.html.erb
<% if(session[:admin]) %>
    <div class="row">
      <h3><i class="fa fa-street-view"></i> Manage your menus</h3>
      <ul class="nav nav-tabs">
        <li role="presentation"><a href="<%= welcome_index_path %>"><i class="fa fa-tachometer"></i> <%=t :Dashboard %></a></li>
        <li role="presentation"><a href="<%= edit_user_path(current_user) %>"><i class="fa fa-user"></i> <%=t :AccountSettings %></a></li>
        <li role="presentation"><a href="<%= edit_chef_path(@chef) %>"><i class="fa fa-street-view"></i> <%=t :ManageYourProfile %></a></li>
        <li role="presentation" class="active"><a href="<%= chef_menus_path(@chef) %>"><i class="fa fa-cutlery"></i> <%=t :ManageYourMenus %></a></li>
        <li role="presentation"><a href="<%= pending_path %>"><i class="fa fa-cart-plus"></i> <%=t :PendingOrders %></a></li>
        <li role="presentation"><a href="<%= overview_path %>"><i class="fa fa-shopping-cart"></i> <%=t :OrderOverview %></a></li>
      </ul>
    </div>

    <div class="row">
      <p></p>
      <div class="alert alert-info " role="alert">
        <strong><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
          <%=t :MenuEditMsg %></strong>
      </div>
    </div>

<% end %>

<%= bootstrap_form_for :menu, url: chef_menu_path, method: :patch do |f| %>

    <% if @menu.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= pluralize(@menu.errors.count, "error") %> prohibited
          this menu from being saved:
          <ul>
            <% @menu.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!--Basics-->
    <div class="page-header"><h5>Basics</h5></div>

    <div class="form-group">
      <%= f.label t(:AdminMenuName) %>
      <%= f.text_field :name, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminMenuCurrency) %>
      <%= f.select :currency, ['PEN', 'GBP', 'USD', 'EUR'], :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminMenuPrice) %>
      <%= f.text_field :price, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminMenuDescription) %>
      <%= f.text_area :description, :class => 'form-control', hide_label: true %>


      <div class="form-group">
        <%= f.label t(:EventTypeMenus) %>
        <%= f.select :eventtype, ['Breakfast', 'Brunch', 'Lunch', 'Dinner', 'Appetizers'], :class => 'form-control', hide_label: true %>
      </div>

    <div class="page-header"><h5>Images</h5></div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto1) %>
      <%= f.file_field :photo1, :class => 'form-control', hide_label: true %>
    </div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto2) %>
      <%= f.file_field :photo2, :class => 'form-control', hide_label: true %>
    </div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto3) %>
      <%= f.file_field :photo3, :class => 'form-control', hide_label: true %>
    </div>
    <!-- Used comment to hide all non-required fields for the moment
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto4) %>
      <%= f.file_field :photo4, :class => 'form-control', hide_label: true %>
    </div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto5) %>
      <%= f.file_field :photo5, :class => 'form-control', hide_label: true %>
    </div>-->



    <div class="page-header"><h5>Additional information</h5></div>

    <div class="form-group">
      <p><%=t :AdditionalInfoMsg %></p>
      <%= f.label t(:AdminMenuPartysize) %>
      <%= f.text_field :partysize, :class => 'form-control', hide_label: true %>
    </div>

    <p><%=t :CuisineExplMsg %></p>
    <div class="form-group">
      <%= f.label t(:Italian) %>
      <%= f.check_box :cuisine_italian%>
    </div>
    <div class="form-group">
      <%= f.label t(:Peruvian) %>
      <%= f.check_box :cuisine_peruvian %>
    </div>
    <div class="form-group">
      <%= f.label t(:Mediterranean) %>
      <%= f.check_box :cuisine_mediterranean%>
    </div>
    <div class="form-group">
      <%= f.label t(:Spanish) %>
      <%= f.check_box :cuisine_spanish%>
    </div>
    <div class="form-group">
      <%= f.label t(:American) %>
      <%= f.check_box :cuisine_american%>
    </div>
    <div class="form-group">
      <%= f.label t(:Japanese) %>
      <%= f.check_box :cuisine_japanese%>
    </div>
    <div class="form-group">
      <%= f.label t(:Fusion) %>
      <%= f.check_box :cuisine_fusion%>
    </div>
    <div class="form-group">
      <%= f.label t(:Thai) %>
      <%= f.check_box :cuisine_thai%>
    </div>
    <div class="form-group">
      <%= f.label t(:Vietnamese) %>
      <%= f.check_box :cuisine_vietnamese%>
    </div>
    <div class="form-group">
      <%= f.label t(:Latinamerican) %>
      <%= f.check_box :cuisine_latinamerican%>
    </div>
    <div class="form-group">
      <%= f.label t(:Indian) %>
      <%= f.check_box :cuisine_indian%>
    </div>
    <div class="form-group">
      <%= f.label t(:Persian) %>
      <%= f.check_box :cuisine_persian%>
    </div>
    <div class="form-group">
      <%= f.label t(:BBQ) %>
      <%= f.check_box :cuisine_bbq%>
    </div>
    <div class="form-group">
      <%= f.label t(:Argentinian) %>
      <%= f.check_box :cuisine_argentinian%>
    </div>
    <div class="form-group">
      <%= f.label t(:Anticuchos) %>
      <%= f.check_box :cuisine_anticuchos%>
    </div>
    <div class="form-group">
      <%= f.label t(:Patisserie) %>
      <%= f.check_box :cuisine_patisserie%>
    </div>
    <div class="form-group">
      <%= f.label t(:Exotic) %>
      <%= f.check_box :cuisine_exotic%>
    </div>
    <div class="form-group">
      <%= f.label t(:German) %>
      <%= f.check_box :cuisine_german%>
    </div>
    <div class="form-group">
      <%= f.label t(:Brazilian) %>
      <%= f.check_box :cuisine_brazilian%>
    </div>

    <div class="form-group">
      <% if(!session[:admin]) %><%= link_to t(:back), chef_menus_path, class: "btn btn-primary" %><% end %>
      <%= f.submit class: "btn btn-success" %>
    </div>

    <h3>To help you, you can see where your input will show on your events page</h3>
    <img src="//s3-sa-east-1.amazonaws.com/losibaritas/admin/Event-Menu-View.png" class="img img-responsive img-center">

<% end %>

app/views/menus/index.html.erb
<% if(session[:admin]) %>
    <div class="row">
      <h3><i class="fa fa-street-view"></i> Manage your menus</h3>
      <ul class="nav nav-tabs">
        <li role="presentation"><a href="<%= welcome_index_path %>"><i class="fa fa-tachometer"></i> <%=t :Dashboard %></a></li>
        <li role="presentation"><a href="<%= edit_user_path(current_user) %>"><i class="fa fa-user"></i> <%=t :AccountSettings %></a></li>
        <li role="presentation"><a href="<%= edit_chef_path(@chef) %>"><i class="fa fa-street-view"></i> <%=t :ManageYourProfile %></a></li>
        <li role="presentation" class="active"><a href="<%= chef_menus_path(@chef) %>"><i class="fa fa-cutlery"></i> <%=t :ManageYourMenus %></a></li>
        <li role="presentation"><a href="<%= pending_path %>"><i class="fa fa-cart-plus"></i> <%=t :PendingOrders %></a></li>
        <li role="presentation"><a href="<%= overview_path %>"><i class="fa fa-shopping-cart"></i> <%=t :OrderOverview %></a></li>
      </ul>
    </div>

    <div class="row">
      <p></p>
      <div class="alert alert-info " role="alert">
        <strong><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
          <%=t :MenuIndexMsg %></strong>
      </div>
    </div>
<% end %>
<div class="row">
  <p></p>
  <p>
<% if(!session[:admin])%><%= link_to t(:back), chefs_path, class: 'btn btn-primary' %><% end %>
<%= link_to t(:AddMenu), new_chef_menu_path(@chef), class: 'btn btn-success' %>
</p>

<table class="table table-striped">
  <tr>
    <th><%=t :AdminMenuName %></th>
    <th><%=t :AdminMenuPrice %></th>
    <th colspan="4"><%=t :Actions %></th>
  </tr>
  <% @chef.menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.currency %> <%= menu.price %></td>
        <td><%= link_to t(:Details), chef_menu_path(menu.chef, menu) %></td>
        <td><%= link_to t(:AdminEditMenu), edit_chef_menu_path(menu.chef, menu) %></td>
        <td><%= link_to t(:Delete), [menu.chef, menu], method: :delete, data: { confirm: t(:DeleteMsg) } %></td>
        <td><%= link_to t(:ManageCourses), chef_menu_courses_path(@chef, menu) %></td>
      </tr>
  <% end %>
</table>
</div>

app/views/menus/new.html.erb
<% if(session[:admin]) %>
    <div class="row">
      <h3><i class="fa fa-street-view"></i> Manage your menus</h3>
      <ul class="nav nav-tabs">
        <li role="presentation"><a href="<%= welcome_index_path %>"><i class="fa fa-tachometer"></i> <%=t :Dashboard %></a></li>
        <li role="presentation"><a href="<%= edit_user_path(current_user) %>"><i class="fa fa-user"></i> <%=t :AccountSettings %></a></li>
        <li role="presentation"><a href="<%= edit_chef_path(@chef) %>"><i class="fa fa-street-view"></i> <%=t :ManageYourProfile %></a></li>
        <li role="presentation" class="active"><a href="<%= chef_menus_path(@chef) %>"><i class="fa fa-cutlery"></i> <%=t :ManageYourMenus %></a></li>
        <li role="presentation"><a href="<%= pending_path %>"><i class="fa fa-cart-plus"></i> <%=t :PendingOrders %></a></li>
        <li role="presentation"><a href="<%= overview_path %>"><i class="fa fa-shopping-cart"></i> <%=t :OrderOverview %></a></li>
      </ul>
    </div>
<% end %>

<h1>Add new menu</h1>

<%= bootstrap_form_for :menu, url: chef_menus_path do |f| %>

    <% if @menu.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= pluralize(@menu.errors.count, "error") %> prohibited
          this menu from being saved:
          <ul>
            <% @menu.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!--Basics-->

    <div class="page-header"><h5>Basics</h5></div>

    <div class="form-group">
      <%= f.label t(:AdminMenuName) %>
      <%= f.text_field :name, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminMenuCurrency) %>
      <%= f.select :currency, ['PEN', 'GBP', 'USD', 'EUR'], :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminMenuPrice) %>
      <%= f.text_field :price, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminMenuDescription) %>
      <%= f.text_area :description, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:EventTypeMenus) %>
      <%= f.select :eventtype, ['Breakfast', 'Brunch', 'Lunch', 'Dinner', 'Appetizers'], :class => 'form-control', hide_label: true %>
    </div>

    <div class="page-header"><h5>Images</h5></div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto1) %>
      <%= f.file_field :photo1, :class => 'form-control', hide_label: true %>
    </div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto2) %>
      <%= f.file_field :photo2, :class => 'form-control', hide_label: true %>
    </div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto3) %>
      <%= f.file_field :photo3, :class => 'form-control', hide_label: true %>
    </div>
    <!-- Used comment to hide all non-required fields for the moment
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto4) %>
    <%= f.file_field :photo4, :class => 'form-control', hide_label: true %>
    </div>
    <div class="form-group">
      <%= f.label t(:AdminMenuPhoto5) %>
    <%= f.file_field :photo5, :class => 'form-control', hide_label: true %>
    </div>-->



    <div class="page-header"><h5>Additional information</h5></div>

    <div class="form-group">
      <p><%=t :AdditionalInfoMsg %></p>
      <%= f.label t(:AdminMenuPartysize) %>
    <%= f.text_field :partysize, :class => 'form-control', hide_label: true %>
    </div>

    <p><%=t :CuisineExplMsg %></p>
    <div class="form-group">
      <%= f.label t(:Italian) %>
    <%= f.check_box :cuisine_italian%>
    </div>
    <div class="form-group">
      <%= f.label t(:Peruvian) %>
    <%= f.check_box :cuisine_peruvian %>
    </div>
    <div class="form-group">
      <%= f.label t(:Mediterranean) %>
    <%= f.check_box :cuisine_mediterranean%>
    </div>
    <div class="form-group">
      <%= f.label t(:Spanish) %>
    <%= f.check_box :cuisine_spanish%>
    </div>
    <div class="form-group">
      <%= f.label t(:American) %>
    <%= f.check_box :cuisine_american%>
    </div>
    <div class="form-group">
      <%= f.label t(:Japanese) %>
    <%= f.check_box :cuisine_japanese%>
    </div>
    <div class="form-group">
      <%= f.label t(:Fusion) %>
    <%= f.check_box :cuisine_fusion%>
    </div>
    <div class="form-group">
      <%= f.label t(:Thai) %>
    <%= f.check_box :cuisine_thai%>
    </div>
    <div class="form-group">
      <%= f.label t(:Vietnamese) %>
    <%= f.check_box :cuisine_vietnamese%>
    </div>
    <div class="form-group">
      <%= f.label t(:Latinamerican) %>
    <%= f.check_box :cuisine_latinamerican%>
    </div>
    <div class="form-group">
      <%= f.label t(:Indian) %>
    <%= f.check_box :cuisine_indian%>
    </div>
    <div class="form-group">
      <%= f.label t(:Persian) %>
    <%= f.check_box :cuisine_persian%>
    </div>
    <div class="form-group">
      <%= f.label t(:BBQ) %>
    <%= f.check_box :cuisine_bbq%>
    </div>
    <div class="form-group">
      <%= f.label t(:Argentinian) %>
    <%= f.check_box :cuisine_argentinian%>
    </div>
    <div class="form-group">
      <%= f.label t(:Anticuchos) %>
    <%= f.check_box :cuisine_anticuchos%>
    </div>
    <div class="form-group">
      <%= f.label t(:Patisserie) %>
    <%= f.check_box :cuisine_patisserie%>
    </div>
    <div class="form-group">
      <%= f.label t(:Exotic) %>
    <%= f.check_box :cuisine_exotic%>
    </div>
    <div class="form-group">
      <%= f.label t(:German) %>
    <%= f.check_box :cuisine_german%>
    </div>
    <div class="form-group">
      <%= f.label t(:Brazilian) %>
    <%= f.check_box :cuisine_brazilian%>
    </div>

    <div class="form-group">
      <% if(!session[:admin]) %><%= link_to t(:back), chef_menus_path, class: "btn btn-primary" %><% end %>
      <%= f.submit class: "btn btn-success" %>
    </div>

    <h3>To help you, you can see where your input will show on your events page</h3>
    <img src="//s3-sa-east-1.amazonaws.com/losibaritas/admin/Event-Menu-View.png" class="img img-responsive img-center">
<% end %>

app/views/menus/show.html.erb
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="row">
              <div class="col-md-12">
                <div class="row">
                  <div class="col-md-2"></div>
                  <div class="col-md-8">
                    <img src="<%=@chef.picture%>" class="img-circle img-center img-responsive">
                  </div>
                  <div class="col-md-2"></div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <h1 class="text-center"><%=@chef.name%></h1>
                    <p><%=@chef.biography%></p>

                    <table class="table">

                      <tr><td><i class="fa fa-money "></i></td> <td>
                        S./ <%=@menu.price%> <%=t(:PerPerson)%></td></tr>
                      <tr><td><i class="fa fa-users"></i></td> <td><%= @menu.partysize%> <%=t(:Persons)%></td></tr>
                    </table>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12 hidden-xs hidden-md text-center">
                    <%= link_to t(:MenuBookNow), orders_new_path(menu_id: @menu.id, type: 'enquiry'), class: 'btn btn-large btn-primary', style: 'color:#FFF' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-12">
                <%= link_to t(:MenuBookNow), orders_new_path(menu_id: @menu.id, type: 'enquiry'), class: 'btn btn-large btn-primary center-block', style: 'color:#FFF' %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <h1 class="text-center"><%=@menu.name%></h1>
              </div>
            </div>

            <div class="row hidden-xs">
              <div class="col-md-12">
                <div class="col-md-12">
                  <div class="col-md-12">
                    <div id="carousel-example" class="carousel slide" data-ride="carousel" data-interval="5000">
                      <div class="carousel-inner">
                        <%if @menu.photo1.present?%>
                            <div class="item active">
                              <img src="<%=@menu.photo1%>">
                            </div>
                        <%end%>
                        <%if @menu.photo2.present? %>
                            <div class="item">
                              <img src="<%=@menu.photo2%>">
                            </div>
                        <% end %>
                        <%if @menu.photo3.present? %>
                            <div class="item">
                              <img src="<%=@menu.photo3%>">
                            </div>
                        <% end %>

                      </div>
                      <a class="left carousel-control" href="#carousel-example" data-slide="prev"><i class="icon-prev  fa fa-angle-left"></i></a>
                      <a class="right carousel-control" href="#carousel-example" data-slide="next"><i class="icon-next fa fa-angle-right"></i></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>


            <% @menu.courses.each do |course| %>
                <div class="row">
                  <div class="col-md-12">
                    <h2 class="text-center"><%=course.name%></h2>
                    <p class="text-center"><%=course.description%></p>
                  </div>
                </div>
            <% end %>


            <div class="row">
              <div class="col-md-12">
                <%= link_to t(:MenuBookNow), orders_new_path(menu_id: @menu.id, type: 'enquiry'), class: 'btn btn-large btn-primary center-block', style: 'color:#FFF' %>
              </div>
              <div>
                <p class="text-center"><i><br>Se debe reservar con un mínimo de 7 días de anticipación<br>
                  El precio por persona no incluye mozos, menaje y bebidas (alcohólicas y no alcohólicas)</i> </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1 class="text-primary text-center"><%= t(:LContactUs)%></h1>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-md-1"></div>
          <div class="col-md-2 text-center">
            <a href="https://instagram.com/losibaritas"><i class="fa fa-5x fa-fw fa-instagram"></i></a>
          </div>
          <div class="col-md-2">
            <a href="https://twitter.com/losibaritas"><i class="fa fa-5x fa-fw fa-twitter"></i></a>
          </div>
          <div class="col-md-2">
            <a href="https://www.facebook.com/losibaritas"><i class="fa fa-5x fa-fw fa-facebook"></i></a>
          </div>
          <div class="col-md-2">
            <a href="http://losibaritas.tumblr.com/"><i class="fa fa-5x fa-fw fa-tumblr"></i></a>
          </div>
          <div class="col-md-2 text-center">
            <a href="mailto:sibaritas.chefs@gmail.com"><i class="fa fa-5x fa-fw hub fa-envelope-o"></i></a>
          </div>
          <div class="col-md-1"></div>
        </div>
      </div>
    </div>