config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  resources :events

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'pending' => 'orders#pending'

  get 'overview' => 'orders#overview'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get 'users/edit'

  get 'orders/index'

  get 'orders/new'

  get 'orders/edit'

  get 'orders/show'

  get 'orders/accept'

  get 'orders/decline'

  get 'searches/index'

  get 'searches/ask'

  get 'searches/result'

  get 'courses/index'

  get 'courses/edit'

  get 'courses/new'

  get 'courses/show'

  get 'menus/index'

  get 'menus/edit'

  get 'menus/new'

  get 'menus/show'

  get 'menu/index'

  get 'menu/new'

  get 'menu/edit'

  get 'menu/shot'

  get 'chefs/new'

  get 'welcome/index'

  get 'welcome/admin'

  get 'landing', to: 'events#landing'

  get 'cheflanding', to: 'events#cheflanding'

  resources :chefs do
    resources :menus do
      resources :courses
    end
  end

  resources :searches

  resources :orders

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :charges

  resources :subscribers

  root 'searches#ask'

  scope "(:locale)", locale: /en|es/ do
    resources :chefs
    resources :orders
    resources :searches
    resources :events
  end
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  belongs_to :user
  has_many :menus, dependent: :destroy

  mount_uploader :picture, ChefPictureUploader
  mount_uploader :video, ChefPictureUploader

  validates :name, presence: true

  def create
    chef = Chef.new(chef_params)

    chef.save
    redirect_to @chef
  end

  private
  def chef_params
    params.require(:chef).permit(:name, :email, :age, :location, :styles, :biography, :culinarytraining, :picture, :video, :family_dinner,
                                 :informal_reunion, :number_of_helpers, :last_minute, :teaching, :min_size, :max_size, :facebook)
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "borussia", only: :index
  layout "admin", except: [:show]

  def index
    @chefs = Chef.all
  end

  def show
    @chef = Chef.find(params[:id])
  end

  def new
    @chef = Chef.new
  end

  def edit
    @chef = Chef.find(params[:id])
  end

  def update
    @chef = Chef.find(params[:id])

    if @chef.update(chef_params)
      redirect_to @chef
    else
      render 'edit'
    end
  end

  def create
    @chef = Chef.new(chef_params)

    if @chef.save
      redirect_to @chef
    else
      render 'new'
    end
  end

  def destroy
    @chef = Chef.find(params[:id])
    @chef.destroy

    redirect_to chefs_path
  end

  private
  def chef_params
    params.require(:chef).permit(:name, :email, :age, :location, :styles, :biography, :culinarytraining, :picture, :video, :family_dinner,
    :informal_reunion, :number_of_helpers, :last_minute, :teaching, :min_size, :max_size, :facebook)
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/edit.html.erb
<% if(session[:admin]) %>
    <div class="row">
      <h3><i class="fa fa-street-view"></i> Manage your chef profile</h3>
      <ul class="nav nav-tabs">
        <li role="presentation"><a href="<%= welcome_index_path %>"><i class="fa fa-tachometer"></i> <%=t :Dashboard %></a></li>
        <li role="presentation"><a href="<%= edit_user_path(current_user) %>"><i class="fa fa-user"></i> <%=t :AccountSettings %></a></li>
        <li role="presentation" class="active"><a href="<%= edit_chef_path(@chef) %>"><i class="fa fa-street-view"></i> <%=t :ManageYourProfile %></a></li>
        <li role="presentation"><a href="<%= chef_menus_path(@chef) %>"><i class="fa fa-cutlery"></i> <%=t :ManageYourMenus %></a></li>
        <li role="presentation"><a href="<%= pending_path %>"><i class="fa fa-cart-plus"></i> <%=t :PendingOrders %></a></li>
        <li role="presentation"><a href="<%= overview_path %>"><i class="fa fa-shopping-cart"></i> <%=t :OrderOverview %></a></li>
      </ul>
    </div>

    <div class="row">
      <p></p>
      <div class="alert alert-info " role="alert">
        <strong><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
          <%=t :ChefEditFlashMsg %></strong>
      </div>
    </div>

    <div class="row">
      <p></p><%= link_to t(:PreviewChef), chef_path(@chef), target: 'blank', class: 'btn btn-success' %><p></p>
    </div>
<% end %>



<%= bootstrap_form_for :chef, url: chef_path(@chef), method: :patch do |f| %>

<% if @chef.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= pluralize(@chef.errors.count, "error") %> prohibited
          this chef from being saved:
          <ul>
            <% @chef.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
<% end %>

    <!-- Disabled per comment all currently not-required fields -->
    <div>
      <%= f.label t(:AdminName) %>
      <%= f.text_field :name, :class => 'form-control', hide_label: true %>
    </div>

    <div>
      <%= f.label t(:AdminEmail) %>
      <%= f.email_field :email, :class => 'form-control', hide_label: true %>
    </div>


    <div class="form-group">
      <%= f.label t(:AdminLocation) %>
      <%= f.select :location, ['Perú', 'United Kingdom', 'France'], :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminBibliography) %>
      <%= f.text_area :biography, :class => 'form-control', hide_label: true %>
    </div>


    <div class="form-group">
      <%= f.label t(:AdminCulinaryTraining) %>
      <%= f.text_area :culinarytraining, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminStyles) %>
      <%= f.text_area :styles, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminPicture) %>
      <%= f.file_field :picture, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminVideo) %>
      <%= f.file_field :video, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%=t :FacebookExplanation %>
      <%= f.label t(:AdminFacebook) %>
      <%= f.url_field :facebook, :class => 'form-control', hide_label: true %>
    </div>
    <!--Service-->
<!--
    <div class="form-group">
      <%=t :TeachingExplanation %>
      <%= f.check_box :teaching, hide_label: true %>
      <%= f.label :teaching, t(:AdminTeaching) %>
    </div>


    <div class="form-group">
      <%=t :HelpersExplanation %>
      <%= f.label t(:AdminNumberOfHelpers) %>
      <%= f.text_field :number_of_helpers, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%=t :MinExplanation %>
      <%= f.label t(:AdminMinSize) %>
      <%= f.text_field :min_size, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%=t :MaxExplanation %>
      <%= f.label t(:AdminMaxSize) %>
      <%= f.text_field :max_size, :class => 'form-control', hide_label: true %>
    </div>
-->
    <div class="form-group">
      <% if(!session[:admin])%>
          <%= link_to t(:back), chefs_path, class: 'btn btn-primary' %>
      <% end %>
      <%= f.submit t(:AdminSaveChef), class: 'btn btn-success' %>
    </div>
    <h3>To help you, you can see where your input will show on your events page</h3>
    <img src="//s3-sa-east-1.amazonaws.com/losibaritas/admin/Event-Chef-View.png" class="img img-responsive img-center">
<% end %>

app/views/chefs/index.html.erb
<h1>Chef overview</h1>

<p>
<%= link_to 'Add chef', new_chef_path, class: 'btn btn-success' %>
</p>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Location</th>
    <th>Styles</th>
    <th colspan="4">Actions</th>
  </tr>

  <% @chefs.each do |chef| %>
      <tr>
        <td><%= chef.name %></td>
        <td><%= chef.age %></td>
        <td><%= chef.location %></td>
        <td><%= chef.styles %></td>
        <td><%= link_to 'Details', chef_path(chef) %></td>
        <td><%= link_to 'Edit', edit_chef_path(chef) %></td>
        <td><%= link_to 'Delete', chef_path(chef), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Manage menus', chef_menus_path(chef) %></td>
      </tr>
  <% end %>
</table>

app/views/chefs/new.html.erb
<h2>New chef</h2>

<%= bootstrap_form_for :chef, url: chefs_path do |f| %>

<% if @chef.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= pluralize(@chef.errors.count, "error") %> prohibited
          this chef from being saved:
          <ul>
            <% @chef.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
<% end %>



    <!--Basics-->
    <!-- Disabled per comment all currently not-required fields -->
    <div>
      <%= f.label t(:AdminName) %>
      <%= f.text_field :name, :class => 'form-control', hide_label: true %>
    </div>

    <div>
      <%= f.label t(:AdminEmail) %>
      <%= f.email_field :email, :class => 'form-control', hide_label: true %>
    </div>


    <div class="form-group">
      <%= f.label t(:AdminLocation) %>
    <%= f.select :location, ['Perú', 'United Kingdom', 'France'], :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminBibliography) %>
      <%= f.text_area :biography, :class => 'form-control', hide_label: true %>
    </div>

    <!--
    <div class="form-group">
      <%= f.label t(:AdminCulinaryTraining) %>
    <%= f.text_area :culinarytraining, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminStyles) %>
    <%= f.text_area :styles, :class => 'form-control', hide_label: true %>
    </div>
    -->
    <div class="form-group">
      <%= f.label t(:AdminPicture) %>
      <%= f.file_field :picture, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:AdminVideo) %>
    <%= f.file_field :video, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%=t :FacebookExplanation %>
    <%= f.label t(:AdminFacebook) %>
    <%= f.url_field :facebook, :class => 'form-control', hide_label: true %>
    </div>
    <!--Service-->
    <!--
    <div class="form-group">
      <%=t :TeachingExplanation %>
    <%= f.check_box :teaching, hide_label: true %>
    <%= f.label :teaching, t(:AdminTeaching) %>
    </div>


    <div class="form-group">
      <%=t :HelpersExplanation %>
    <%= f.label t(:AdminNumberOfHelpers) %>
    <%= f.text_field :number_of_helpers, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%=t :MinExplanation %>
    <%= f.label t(:AdminMinSize) %>
    <%= f.text_field :min_size, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%=t :MaxExplanation %>
    <%= f.label t(:AdminMaxSize) %>
    <%= f.text_field :max_size, :class => 'form-control', hide_label: true %>
    </div>
-->
    <div class="form-group">
      <% if(!session[:admin])%>
          <%= link_to t(:back), chefs_path, class: 'btn btn-primary' %>
      <% end %>
      <%= f.submit t(:AdminSaveChef), class: 'btn btn-success' %>
    </div>
    <h3>To help you, you can see where your input will show on your events page</h3>
    <img src="//s3-sa-east-1.amazonaws.com/losibaritas/admin/Event-Chef-View.png" class="img img-responsive img-center">
<% end %>

app/views/chefs/show.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.5&appId=1564821780431761";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- Page Content -->
<div class="container">

  <hr>
  <div class="row">
    <div class="col-sm-12"><%= link_to t(:back), :back, class: 'btn btn-primary' %></div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <h2><%=@chef.name%></h2>
      <p><strong><%=t :ChefLocation%> </strong> <%= @chef.location %> <strong><%=t :ChefStyles%> </strong>
        <%= @chef.styles %>
      <p><strong><%=t :ChefBiography%> </strong> <%= @chef.biography %></p>

      <p><strong><%=t :CulinaryTraining%> </strong> <%= @chef.culinarytraining %></p>

    </div>
    <div class="col-sm-4 text-center">
      <% if @chef.picture %><img src="<%= @chef.picture %>" alt="" class="center-block img-circle img-thumbnail img-responsive"><% end %>
      <% if @chef.facebook %>
      <p>
        <br>
        <a href="<%=@chef.facebook%>"><i class="fa fa-facebook fa-2x"></i></a>
        <br>
      </p>
      <% end %>

    </div>
  </div>
  <!-- /.row -->

  <hr>


  <div class="row">
    <h2><%=t :ChefTheMenus%></h2>
    <div class="container-fluid">
      <div class="row text-center">
        <h3 style="color:white;font-family:verdana;">Snap Tight Image Tiles (Responisve)</h3>
      </div>
      <div class="row">
        <% @chef.menus.each_with_index do |menu, index| %>
            <% if index < 2 then @tilesize=6 end %>
            <% if index > 1 && index < 6 then @tilesize=3 end %>
            <%= link_to chef_menu_path(menu.chef, menu) do %>
            <div class="cover-card col-sm-<%=@tilesize%>" style="background: url(<%=menu.photo1%>) no-repeat center top;background-size:cover;">
          <p><strong><%=menu.name%></strong></p>
        </div><% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <h2>Comentarios</h2>
  </div>
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <div class="fb-comments" data-href="https://www.losibaritas.com/chefs/<%=@chef.id%>" data-numposts="5"></div>
    </div>
    <div class="col-md-2"></div>
  </div>


  <hr>
  <%= link_to t(:back), :back, class: 'btn btn-primary' %>
  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; LoSibaritas 2015</p>
      </div>
    </div>
    <!-- /.row -->
  </footer>
</div>