config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  resources :events

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'pending' => 'orders#pending'

  get 'overview' => 'orders#overview'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get 'users/edit'

  get 'orders/index'

  get 'orders/new'

  get 'orders/edit'

  get 'orders/show'

  get 'orders/accept'

  get 'orders/decline'

  get 'searches/index'

  get 'searches/ask'

  get 'searches/result'

  get 'courses/index'

  get 'courses/edit'

  get 'courses/new'

  get 'courses/show'

  get 'menus/index'

  get 'menus/edit'

  get 'menus/new'

  get 'menus/show'

  get 'menu/index'

  get 'menu/new'

  get 'menu/edit'

  get 'menu/shot'

  get 'chefs/new'

  get 'welcome/index'

  get 'welcome/admin'

  get 'landing', to: 'events#landing'

  get 'cheflanding', to: 'events#cheflanding'

  resources :chefs do
    resources :menus do
      resources :courses
    end
  end

  resources :searches

  resources :orders

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :charges

  resources :subscribers

  root 'searches#ask'

  scope "(:locale)", locale: /en|es/ do
    resources :chefs
    resources :orders
    resources :searches
    resources :events
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "borussia", only: :index
  layout "admin", only: [:index, :new, :edit]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # Show landing page
  def landing
    @events = Event.all.where.not(:status => 'inactive').order("id DESC")
    @subscriber = Subscriber.new
    render layout: "landing"
  end

  def cheflanding
    render layout: "landing"
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show

    @chef = Chef.find(@event.chef)
    @menu = Menu.find(@event.menu)
  end

  # GET /events/new
  def new
    @chefs = Chef.all
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @chefs = Chef.all
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:chef, :menu, :date, :location, :price, :persons, :email, :status)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :chef %><br>
    <%= f.select :chef, Chef.all.collect {|c| [ c.name, c.id ] }, hide_label: true %>
  </div>

  <div class="field">
    <%= f.label :menu %><br>
    <%= f.select :menu, Menu.all.collect {|m| [ m.name, m.id ] }, hide_label: true %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
    <div class="italic">Text will be shown exactly as entered. E.g. "24 junio 2015"</div>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
    <div class="italic">Text will be shown exactly as entered. E.g. "Lima"</div>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
    <div class="italic">Text will be shown exactly as entered with "por persona" added. E.g. "S./ 149" will be shown as "S./ 149 por persona"</div>
  </div>
  <div class="field">
    <%= f.label :persons %><br>
    <%= f.text_field :persons %>
    <div class="italic">Text will be shown exactly as entered. E.g. "6-14"</div>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, ['active', 'inactive','sold_out'], hide_label: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/cheflanding.erb
<div class="cover">
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><span style="font-family:Handlee; color:#FFF">LoSibaritas</span></a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">

          <li><%= link_to t(:IAmClient), searches_ask_path, style: 'color:#FFF'%></li>
          <li>
            <a href="http://losibaritas.tumblr.com" target="new" style="color:#FFF">Blog</a>
          </li>
          <li><%=link_to 'English', url_for( :locale => 'en' ), style: "color:#FFF"%></li>
          <li><%=link_to 'Castellano', url_for( :locale => 'es' ), style: "color:#FFF"%></li>

        </ul>
      </div>
    </div>
  </div>
  <div class="cover-image" style="background-image : url('https://s3-sa-east-1.amazonaws.com/losibaritas/background99.jpg')"></div>
  <div class="container">

    <div class="section">
      <div class="container">
        <div class="col-md-12">
          <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <h1 class="text-center" style="color:#FFFFFF"><%= t(:LKeepUpdated)%></h1>
          <h3 class="text-center" style="color:#FFFFFF; background-color: #000000; opacity: 0.8"><%= t(:ChefSignUpMsg)%></h3>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-md-12">
          <div class="col-md-4"></div>
          <div class="col-md-4 center-block">
            <%= bootstrap_form_for :subscriber, url: subscribers_path do |f| %>
                <div>
                  <%= f.text_field :email, :class => 'form-control', hide_label: true, placeholder: "Correo electrónico" %>
                  <%= f.hidden_field :clienttype, :value => "chef" %>

                  <%= f.submit t(:SignUp), class: 'btn btn-success' %>
                </div>
            <% end %>
          </div>
          <div class="col-md-4"></div>
        </div>
      </div>
      <div class="row text-center">

      </div>
    </div>
  </div>

  </div>

<!--Quote 1-->
<div class="section">
  <div class="container">
    <div class="row" style="vertical-align: middle">
      <div class="col-md-2"></div>
      <div class="col-md-4">
        <h3 class="text-primary"><i>“Es una gran oportunidad para cocineros. Puedes generar ingresos además de exposición ya que los clientes serán en su mayoría potenciales clientes en el futuro”</i><br>Jaime Pesaque
        </h3>
      </div>
      <div class="col-md-4">
        <img src="//losibaritas.s3.amazonaws.com/uploads/chef/picture/12/Jaime.jpg" class="img-circle img-responsive">
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>

<!--Quote 2-->
<div class="section">
  <div class="container">
    <div class="row" style="vertical-align: middle">
      <div class="col-md-2"></div>
      <div class="col-md-4">
        <img src="//losibaritas.s3.amazonaws.com/uploads/chef/picture/27/JBA0.jpg" class="img-circle img-responsive">
      </div>
      <div class="col-md-4">
        <h3 class="text-primary"><i>“Solo me tuve que encargar de lo que me gusta, cocinar y atender. El resto, promoción y coordinación, ya estaba todo coordinada a través de la página”
        </i><br>James Berckemeyer
        </h3>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>

  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-primary"><%=t(:HowDoesItWorkTitle)%></h1>
          <h3>Haz que tu pasión por la cocina sea rentable.</h3>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-md-4">
          <div class="well"><h4><img class="img-center img-responsive img-circle" src="//s3-sa-east-1.amazonaws.com/losibaritas/chefsteps/step1.png">Arma tu perfil y menús.</h4></div>
        </div>
        <div class="col-md-4">
          <div class="well"><h4><img class="img-center img-responsive img-circle" src="//s3-sa-east-1.amazonaws.com/losibaritas/chefsteps/step2.png">Promociónate en la comunidad LoSibaritas.</h4></div>
        </div>
        <div class="col-md-4">
          <div class="well"><h4><img class="img-center img-responsive img-circle" src="//s3-sa-east-1.amazonaws.com/losibaritas/chefsteps/step3.png">Cocina para diversos clientes.</h4></div>
        </div>
        </div>
        <div class="col-md-12" style="vertical-align: middle">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/e-gCXSLQ1XQ?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>



  <a name="contact"></a>
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-primary text-center"><%= t(:LContactUs)%></h1>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-md-1"></div>
        <div class="col-md-2 text-center">
          <a href="https://instagram.com/losibaritas"><i class="fa fa-5x fa-fw fa-instagram"></i></a>
        </div>
        <div class="col-md-2">
          <a href="https://twitter.com/losibaritas"><i class="fa fa-5x fa-fw fa-twitter"></i></a>
        </div>
        <div class="col-md-2">
          <a href="https://www.facebook.com/losibaritas"><i class="fa fa-5x fa-fw fa-facebook"></i></a>
        </div>
        <div class="col-md-2">
          <a href="http://losibaritas.tumblr.com/"><i class="fa fa-5x fa-fw fa-tumblr"></i></a>
        </div>
        <div class="col-md-2 text-center">
          <a href="mailto:info@losibaritas.com"><i class="fa fa-5x fa-fw hub fa-envelope-o"></i></a>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  </div>


</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Chef</th>
      <th>Menu</th>
      <th>Date</th>
      <th>Location</th>
      <th>Price</th>
      <th>Persons</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= Chef.find(event.chef).name %></td>
        <td><%= Menu.find(event.menu).name %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.price %></td>
        <td><%= event.persons %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class: 'btn btn-success'%>

app/views/events/landing.html.erb
<div class="cover">
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><span style="font-family:Handlee; color:#FFF">LoSibaritas</span></a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">

          <li><%= link_to t(:IAmAChef), cheflanding_path, style: 'color:#FFF'%></li>
          <li><a href="#howdoesitwork" style="color:#FFF"><%=t(:HowDoesItWorkTitle)%></a></li>
          <li><a href="#signup" style="color:#FFF"><%=t(:SignUp)%></a></li>

          <li>
            <a href="http://losibaritas.tumblr.com" target="new" style="color:#FFF">Blog</a>
          </li>
          <li><%=link_to 'English', url_for( :locale => 'en' ), style: "color:#FFF"%></li>
          <li><%=link_to 'Castellano', url_for( :locale => 'es' ), style: "color:#FFF"%></li>

        </ul>
      </div>
    </div>
  </div>
  <div class="cover-image" style="background-image : url('https://s3-sa-east-1.amazonaws.com/losibaritas/launchpage.jpg')"></div>
  <div class="container">
    <div id="carousel-example" class="carousel slide" data-ride="carousel" data-interval="15000">
      <div class="carousel-inner">
        <% @events.each_with_index do |event, index| %>

            <% if index==0%><div class="item active"><% end %>
            <% if index!=0%><div class="item"><% end %>
          <!-- First event -->
          <div class="row">
            <div class="col-md-12 text-center">
              <div class="row">
                <div class="col-md-12">
                  <div class="section">
                    <div class="container">
                      <div class="row">
                        <div class="col-md-12">
                          <h1 class="text-inverse"><%=Chef.find(event.chef).name%> <%= t(:LTitle)%></h1>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                          <% if event.status == 'active' %>
                              <a href="<%=event_path(event)%>"><img src="<%=Chef.find(event.chef).picture%>" class="img-circle img-responsive"></a>
                          <% end %>
                          <% if event.status == 'sold_out' %>
                              <a href="#signup"><img src="<%=Chef.find(event.chef).picture%>" class="img-circle img-responsive"></a>
                          <% end %>

                        </div>
                        <div class="col-md-4"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <p class="text-inverse"><i class="fa fa-map-marker"></i> <%=event.location%> - <i class="fa fa-calendar"></i> <%=event.date%> - <i class="fa fa-money "></i> <%=event.price%> por persona</p>
              <br>


              <% if event.status == 'active' %>
              <%= link_to t(:MenuDiscover), searches_path, class: 'btn btn-lg btn-primary', style: 'color:#FFF' %>
              <% end %>

              <% if event.status == 'sold_out' %>
              <a href="#signup" class="btn btn-lg btn-primary" style="color:#FFF"><%=t(:SoldOut)%></a>
              <% end %>

             </div>
              <br>

            </div>
          </div>

        <% end %>


      </div>
      <a class="left carousel-control" href="#carousel-example" data-slide="prev"><i class="icon-prev  fa fa-angle-left"></i></a>
      <a class="right carousel-control" href="#carousel-example" data-slide="next"><i class="icon-next fa fa-angle-right"></i></a>
    </div>


  </div>
</div>

<a name="howdoesitwork"></a>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1 class="text-primary"><%= t(:WhyLoSibaritasTitle)%></h1>
        <p><%= t(:WhyLoSibaritasExpl)%></p>
      </div>
      <div class="col-md-6">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/e-gCXSLQ1XQ?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-primary"><%=t(:HowDoesItWorkTitle)%></h1>
        <h3><%=t(:HowDoesItWorkExpl)%></h3>
        <p>
        <div class="well"><h4><%=t(:HowDoesItWorkReason1)%></h4></div>
        <div class="well"><h4><%=t(:HowDoesItWorkReason2)%></h4></div>
        <div class="well"><h4><%=t(:HowDoesItWorkReason3)%></h4></div>
        <div class="well"><h4><%=t(:HowDoesItWorkReason4)%></h4></div>
        <h3><%=t(:HowDoesItWorkFooter)%> <a href="#"><%=t(:HowDoesItWorkFooterLink)%></a></h3>
        </p>
      </div>
    </div>
  </div>
</div>




<a name="contact"></a>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-primary text-center"><%= t(:LContactUs)%></h1>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-1"></div>
      <div class="col-md-2 text-center">
        <a href="https://instagram.com/losibaritas"><i class="fa fa-5x fa-fw fa-instagram"></i></a>
      </div>
      <div class="col-md-2">
        <a href="https://twitter.com/losibaritas"><i class="fa fa-5x fa-fw fa-twitter"></i></a>
      </div>
      <div class="col-md-2">
        <a href="https://www.facebook.com/losibaritas"><i class="fa fa-5x fa-fw fa-facebook"></i></a>
      </div>
      <div class="col-md-2">
        <a href="http://losibaritas.tumblr.com/"><i class="fa fa-5x fa-fw fa-tumblr"></i></a>
      </div>
      <div class="col-md-2 text-center">
        <a href="mailto:info@losibaritas.com"><i class="fa fa-5x fa-fw hub fa-envelope-o"></i></a>
      </div>
      <div class="col-md-1"></div>
    </div>
  </div>
</div>


<a name="signup"></a>
<div class="section">
  <div class="container">
    <div class="col-md-12">
      <h1 class="text-primary text-center"><%= t(:LKeepUpdated)%></h1>
      <h3 class="text-center"><%= t(:LLeaveYourMail)%></h3>
    </div>
  </div>
  <div class="row text-center">
      <div class="col-md-12">
        <div class="col-md-4"></div>
        <div class="col-md-4 center-block">
        <%= bootstrap_form_for :subscriber, url: subscribers_path do |f| %>
            <div>
              <%= f.text_field :email, :class => 'form-control' %>
              <%= f.hidden_field :clienttype, :value => "customer" %>

              <%= f.submit t(:SignUp), class: 'btn btn-success' %>
            </div>
        <% end %>
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% if @event.status == 'active' %>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-2"></div>
              <div class="col-md-8">
                <img src="<%=@chef.picture%>" class="img-circle img-center img-responsive">
              </div>
              <div class="col-md-2"></div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <h1 class="text-center"><%=@chef.name%></h1>
                <p><%=@chef.biography%></p>

                <table class="table">
                  <tr><td><i class="fa fa-map-marker"></i></td> <td><%=@event.location%></td></tr>
                  <tr><td><i class="fa fa-calendar"></i></td> <td><%=@event.date%></td></tr>
                  <tr><td><i class="fa fa-money "></i></td> <td>
                    <%=@event.price%> <%=t(:PerPerson)%></td></tr>
                  <tr><td><i class="fa fa-users"></i></td> <td><%= @event.persons%> <%=t(:Persons)%></td></tr>
                </table>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 hidden-xs hidden-md text-center">
                <%= link_to t(:MenuBookNow), orders_new_path(menu_id: @menu.id, type: 'event', event_id: @event.id), class: 'btn btn-large btn-primary', style: 'color:#FFF' %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-12">
            <%= link_to t(:MenuBookNow), orders_new_path(menu_id: @menu.id, type: 'event', event_id: @event.id), class: 'btn btn-large btn-primary center-block', style: 'color:#FFF' %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <h1 class="text-center"><%=@menu.name%></h1>
          </div>
        </div>

        <div class="row hidden-xs">
          <div class="col-md-12">
            <div class="col-md-12">
              <div class="col-md-12">
                <div id="carousel-example" class="carousel slide" data-ride="carousel" data-interval="5000">
                  <div class="carousel-inner">
                    <%if @menu.photo1.present?%>
                    <div class="item active">
                      <img src="<%=@menu.photo1%>">
                    </div>
                    <%end%>
                    <%if @menu.photo2.present? %>
                    <div class="item">
                      <img src="<%=@menu.photo2%>">
                    </div>
                    <% end %>
                    <%if @menu.photo3.present? %>
                    <div class="item">
                      <img src="<%=@menu.photo3%>">
                    </div>
                    <% end %>

                  </div>
                  <a class="left carousel-control" href="#carousel-example" data-slide="prev"><i class="icon-prev  fa fa-angle-left"></i></a>
                  <a class="right carousel-control" href="#carousel-example" data-slide="next"><i class="icon-next fa fa-angle-right"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>


        <% @menu.courses.each do |course| %>
            <div class="row">
              <div class="col-md-12">
                <h2 class="text-center"><%=course.name%></h2>
                <p class="text-center"><%=course.description%></p>
              </div>
            </div>
        <% end %>


        <div class="row">
          <div class="col-md-12">
            <%= link_to t(:MenuBookNow), orders_new_path(menu_id: @menu.id, type: 'event', event_id: @event.id), class: 'btn btn-large btn-primary center-block', style: 'color:#FFF' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1 class="text-primary text-center"><%= t(:LContactUs)%></h1>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-md-1"></div>
          <div class="col-md-2 text-center">
            <a href="https://instagram.com/losibaritas"><i class="fa fa-5x fa-fw fa-instagram"></i></a>
          </div>
          <div class="col-md-2">
            <a href="https://twitter.com/losibaritas"><i class="fa fa-5x fa-fw fa-twitter"></i></a>
          </div>
          <div class="col-md-2">
            <a href="https://www.facebook.com/losibaritas"><i class="fa fa-5x fa-fw fa-facebook"></i></a>
          </div>
          <div class="col-md-2">
            <a href="http://losibaritas.tumblr.com/"><i class="fa fa-5x fa-fw fa-tumblr"></i></a>
          </div>
          <div class="col-md-2 text-center">
            <a href="mailto:sibaritas.chefs@gmail.com"><i class="fa fa-5x fa-fw hub fa-envelope-o"></i></a>
          </div>
          <div class="col-md-1"></div>
        </div>
      </div>
    </div>
<% end %>

<% if @event.status == 'inactive' %>
<strong>This event is sold out. Please come back later.</strong>
<% end %>