config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  resources :events

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'pending' => 'orders#pending'

  get 'overview' => 'orders#overview'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get 'users/edit'

  get 'orders/index'

  get 'orders/new'

  get 'orders/edit'

  get 'orders/show'

  get 'orders/accept'

  get 'orders/decline'

  get 'searches/index'

  get 'searches/ask'

  get 'searches/result'

  get 'courses/index'

  get 'courses/edit'

  get 'courses/new'

  get 'courses/show'

  get 'menus/index'

  get 'menus/edit'

  get 'menus/new'

  get 'menus/show'

  get 'menu/index'

  get 'menu/new'

  get 'menu/edit'

  get 'menu/shot'

  get 'chefs/new'

  get 'welcome/index'

  get 'welcome/admin'

  get 'landing', to: 'events#landing'

  get 'cheflanding', to: 'events#cheflanding'

  resources :chefs do
    resources :menus do
      resources :courses
    end
  end

  resources :searches

  resources :orders

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :charges

  resources :subscribers

  root 'searches#ask'

  scope "(:locale)", locale: /en|es/ do
    resources :chefs
    resources :orders
    resources :searches
    resources :events
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
#  validates :name, presence: true

  validates :no_of_guests, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :postalcode, presence: true
  validates :country, presence: true

  def create
    order = Order.new(order_params)

    order.save
    redirect_to @order
  end

  private
  def order_params
    params.require(:order).permit(
        :menu_id, :no_of_guests, :name, :email, :phone, :street, :city, :postalcode, :country, :remarks_sibaritas, :remarks_chef,
        :net_price, :vat_amount, :currency, :cook_date, :cook_time, :cook_location)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout "admin", only: [:index]

  def index
    @orders = Order.all.paginate(page: params[:page], :per_page => 20).order(:created_at).reverse_order
  end

  def show
    @order = Order.find(params[:id])
    @menu = Menu.find(@order.menu_id)

    if(@order.payment_status == 'PAID')
      if(@order.email_status != 'SENT')
        UserMailer.order_request_mail(@order.email, @menu.id, @order.id, params[:locale]).deliver_now!
        @order.update(email_status: 'SENT')
      end
    end
  end

  def new
    @order = Order.new
    @menu = Menu.find(params[:menu_id])
    @order.order_type = params[:type]

    if @order.order_type == 'event'
      @event = Event.find(params[:event_id])
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to orders_path
    else
      render 'edit'
    end
  end

  def create
    @order = Order.new(order_params)

    @order.order_type = params[:type]
    if @order.order_type == 'event'
      @event = Event.find(params[:event_id])
    end

    @menu = Menu.find(params[:menu_id])
    @order.net_price = @order.no_of_guests * @menu.price
    @order.currency = @menu.currency
    @order.vat_amount = @order.net_price * 0.18
    @order.menu_id = @menu.id
    @order.chef_id = @menu.chef_id

    if @order.save
      #Do not send e-mail any more when order is saved
      UserMailer.order_request_mail(@order.email, @menu.id, @order.id, params[:locale]).deliver_now!
      UserMailer.order_request_mail("raul@losibaritas.com", @menu.id, @order.id, params[:locale]).deliver_now!
      #UserMailer.order_chef_action_mail(@order.email, @menu.id, @order.id).deliver_now!

      redirect_to orders_show_path(:id => @order.id)
      #Payment path -> disabled 19 Sep
      #redirect_to new_charge_path(:order_id => @order.id)
    else
      render 'new'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to orders_path
  end

  #view all pending orders
  def pending
    @chef = Chef.find_by_email(current_user.email)
    @orders = Order.all.where(:chef_id => @chef.id).where(:status => 'PENDING').paginate(page: params[:page], :per_page => 20).order(:created_at).reverse_order
  end

  #view all orders of one chef
  def overview
    @chef = Chef.find_by_email(current_user.email)
    @orders = Order.all.where(:chef_id => @chef.id).paginate(page: params[:page], :per_page => 20).order(:created_at).reverse_order
  end

  #accept an order
  def accept
    @order = Order.find(params[:orderid])
    @order.update(:status => 'ACCEPTED')
    UserMailer.order_mail(@order.email, @order.menu_id, @order.id).deliver!
    UserMailer.chef_mail(@order.email, @order.menu_id, @order.id).deliver!
    flash[:success] = "Order accepted"
    redirect_to pending_path
  end

  #decline an order
  def decline
    @order = Order.find(params[:orderid])
    @order.update(:status => 'DECLINED')
    UserMailer.order_reject_mail(@order.email, @order.menu_id, @order.id).deliver!
    flash[:danger] = "Order declined"
    redirect_to pending_path
  end

  private
  def order_params
      params.require(:order).permit(
          :menu_id, :no_of_guests, :name, :email, :phone, :street, :city, :postalcode, :country, :remarks_sibaritas, :remarks_chef,
          :net_price, :vat_amount, :currency, :cook_date, :cook_time, :cook_location, :order_type, :type, :event_id, :payment_status, :email_status)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<h1>Edit order</h1>
<%= bootstrap_form_for :order, url: order_path(@order), method: :patch do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% @order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :status %><br>
      <%= f.select :status, ['DECLINED', 'ACCEPTED','PENDING'], hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label :payment_status %><br>
      <%= f.select :payment_status, ['PAID','NOT_PAID'], hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label :email_status %><br>
      <%= f.select :email_status, ['SENT','NOT_SENT'], hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:OrderNoOfGuests) %>
      <%= f.select :no_of_guests, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], :class => 'form-control', hide_label: true %>
    </div>

    <div class="page-header"><h3><%=t :OrderContactInformation%></h3></div>
    <div class="form-group">
      <%= f.label t(:OrderName) %>
      <%= f.text_field :name, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderEMail) %>
      <%= f.email_field :email, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderPhone) %>
      <%= f.telephone_field :phone, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:OrderStreet) %>
      <%= f.text_field :street, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderCity) %>
      <%= f.text_field :city, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderPostalcode) %>
      <%= f.text_field :postalcode, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderCountry) %>
      <%= f.select :country, ['Peru', 'United Kingdom', 'France'], :class => 'form-control', hide_label: true %>
    </div>

    <h3><%=t :OrderMessage %></h3>
    <div class="form-group">
      <%= f.label t(:OrderRemarksChef) %>
      <%= f.text_area :remarks_chef, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderRemarksSibaritas) %>
      <%= f.text_area :remarks_sibaritas, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= link_to t(:back), landing_path, class: 'btn btn-primary', style: 'color: #FFF' %>
      <%= f.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/orders/index.html.erb
<h1>Orders overview</h1>
<%= will_paginate %>
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Order Date</th>
    <th>Email Status</th>
    <th>Payment Status</th>
    <th>Net Price</th>
    <th colspan="4">Actions</th>
  </tr>

  <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.name %></td>
        <td><%= order.created_at %></td>
        <td><%= order.email_status%></td>
        <td><%= order.payment_status %></td>
        <td><%=order.currency%> <%= order.net_price %></td>
        <td><%= link_to 'Details', order_path(order) %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Delete', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate %>

app/views/orders/new.html.erb
<h4></h4>
<!--
<div class="container">
  <div class="process">
    <div class="process-row">
      <div class="process-step">
        <button type="button" class="btn btn-success btn-circle" disabled="disabled"><i class="fa fa-user fa-3x"></i></button>
        <p>Personal data</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-usd fa-3x"></i></button>
        <p>Payment</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-thumbs-up fa-3x"></i></button>
        <p>Confirmation</p>
      </div>
    </div>
</div>-->

<h2><%=t :OrderOrderMenu %></h2>

<div class="col-lg-12"><div class="well text-center">
  <p>
  <h4><strong><%= @menu.name %></strong></h4>
  <% if @order.order_type == 'event' %>
      <%= @event.price %> <%=t(:PerPerson)%><br>
      <%= t(:OrderCookLocation) %>: <%= @event.location %><br>
      <%= t(:OrderCookDate) %>: <%= @event.date %>
  <% end %>
  </p>
</div></div>

<div class="col-lg-12">
<%= bootstrap_form_for :order, :url => { :action => :create, :type => @order.order_type, :event_id => params[:event_id] } do |f| %>

          <!-- These three field are required for the event based payment and booking. I removed the standard form elements for date/location selection-->


          <%= f.hidden_field :event_id, :value => "999" %>
          <%= f.hidden_field :cook_location, :value => "Dortmund" %>

            <%= f.label t(:OrderCookDate) %>
            <%= f.date_select :cook_date, hide_label: true %>

            <%= f.label t(:OrderCookTime) %>
            <%= f.time_select :cook_time, hide_label: true %>

    <input type="hidden" id="menu_id" name="menu_id" value="<%= @menu.id %>">
    <input type="hidden" id="order_type" name="order_type" value="<%= @order.order_type %>">

      <% if @order.errors.any? %>

        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= pluralize(@order.errors.count, "error") %> prohibited
          this chef from being saved:
          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!--Menu forms-->

    <div class="form-group">


      <%= f.label t(:OrderNoOfGuests) %>
      <%= f.select :no_of_guests, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100], :class => 'form-control', hide_label: true %>
    </div>

    <div class="page-header"><h3><%=t :OrderContactInformation%></h3></div>
    <div class="form-group">
      <%= f.label t(:OrderName) %>
      <%= f.text_field :name, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderEMail) %>
      <%= f.email_field :email, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderPhone) %>
      <%= f.telephone_field :phone, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= f.label t(:OrderStreet) %>
      <%= f.text_field :street, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderCity) %>
      <%= f.text_field :city, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderPostalcode) %>
      <%= f.text_field :postalcode, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderCountry) %>
      <%= f.select :country, ['Peru', 'United Kingdom', 'France'], :class => 'form-control', hide_label: true %>
    </div>

    <h3><%=t :OrderMessage %></h3>
    <div class="form-group">
      <%= f.label t(:OrderRemarksChef) %>
      <%= f.text_area :remarks_chef, :class => 'form-control', hide_label: true %>

      <%= f.label t(:OrderRemarksSibaritas) %>
      <%= f.text_area :remarks_sibaritas, :class => 'form-control', hide_label: true %>
    </div>

    <div class="form-group">
      <%= link_to t(:back), landing_path, class: 'btn btn-primary', style: 'color: #FFF' %>

      <%= f.submit t(:OrderSubmit), :class => 'btn btn-success' %>
    </div>
<% end %>
</div>
    </div>

app/views/orders/overview.html.erb
<div class="row">
  <h3><i class="fa fa-cart-plus"></i><%=t :PendingOrders%></h3>
  <ul class="nav nav-tabs">
    <li role="presentation"><a href="<%= welcome_index_path %>"><i class="fa fa-tachometer"></i> <%=t :Dashboard %></a></li>
    <li role="presentation"><a href="<%= edit_user_path(current_user) %>"><i class="fa fa-user"></i> <%=t :AccountSettings %></a></li>
    <li role="presentation"><a href="<%= edit_chef_path(@chef) %>"><i class="fa fa-street-view"></i> <%=t :ManageYourProfile %></a></li>
    <li role="presentation"><a href="<%= chef_menus_path(@chef) %>"><i class="fa fa-cutlery"></i> <%=t :ManageYourMenus %></a></li>
    <li role="presentation"><a href="<%= pending_path %>"><i class="fa fa-cart-plus"></i> <%=t :PendingOrders %></a></li>
    <li role="presentation" class="active"><a href="<%= overview_path %>"><i class="fa fa-shopping-cart"></i> <%=t :OrderOverview %></a></li>
  </ul>
</div>

<div class="row">
  <p></p>
  <div class="alert alert-info " role="alert">
    <strong><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
      <%=t :OrderOverviewMsg %></strong>
  </div>
</div>

<div class="row">
  <%= will_paginate %>
  <table class="table table-striped">
    <tr>
      <th><%=t :PendingOrdersName %></th>
      <th><%=t :PendingOrdersGuests %></th>
      <th><%=t :PendingOrdersAmount %></th>
      <th><%=t :PendingOrdersOrderDate %> </th>
      <th><%=t :PendingOrdersEventDate %></th>
      <th><%=t :PendingOrdersStatus %></th>
      <th><%=t :Details %></th>
    </tr>

    <% @orders.each do |order| %>
        <tr>
          <td><%= order.name %></td>
          <td><%= order.no_of_guests %></td>
          <td><%= order.currency %> <%= order.net_price %></td>
          <td><%= order.created_at %></td>
          <td><%= order.cook_date %></td>
          <td><%= order.status %></td>
          <td><%= link_to t(:Details), order_path(order), target: 'blank' %></td>
        </tr>


    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/orders/pending.html.erb
<div class="row">
  <h3><i class="fa fa-cart-plus"></i><%=t :PendingOrders%></h3>
  <ul class="nav nav-tabs">
    <li role="presentation"><a href="<%= welcome_index_path %>"><i class="fa fa-tachometer"></i> <%=t :Dashboard %></a></li>
    <li role="presentation"><a href="<%= edit_user_path(current_user) %>"><i class="fa fa-user"></i> <%=t :AccountSettings %></a></li>
    <li role="presentation"><a href="<%= edit_chef_path(@chef) %>"><i class="fa fa-street-view"></i> <%=t :ManageYourProfile %></a></li>
    <li role="presentation"><a href="<%= chef_menus_path(@chef) %>"><i class="fa fa-cutlery"></i> <%=t :ManageYourMenus %></a></li>
    <li role="presentation" class="active"><a href="<%= pending_path %>"><i class="fa fa-cart-plus"></i> <%=t :PendingOrders %></a></li>
    <li role="presentation"><a href="<%= overview_path %>"><i class="fa fa-shopping-cart"></i> <%=t :OrderOverview %></a></li>
  </ul>
</div>

<div class="row">
  <p></p>
  <div class="alert alert-info " role="alert">
    <strong><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
      <%=t :PendingOrdersMsg %></strong>
  </div>
</div>

<div class="row">
  <%= will_paginate %>
<table class="table table-striped">
  <tr>
    <th><%=t :PendingOrdersName %></th>
    <th><%=t :PendingOrdersGuests %></th>
    <th><%=t :PendingOrdersAmount %></th>
    <th><%=t :PendingOrdersOrderDate %> </th>
    <th><%=t :PendingOrdersEventDate %></th>
    <th><%=t :PendingOrdersStatus %></th>
    <th colspan="3"><%=t :Actions %></th>
  </tr>

  <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.no_of_guests %></td>
        <td><%= order.currency %> <%= order.net_price %></td>
        <td><%= order.created_at %></td>
        <td><%= order.cook_date %></td>
        <td><%= order.status %></td>
        <td><%= link_to t(:Details), order_path(order), target: 'blank' %></td>
        <td><%= link_to t(:PendingOrdersAccept), orders_accept_path(:orderid => order.id) %></td>
        <td><%= link_to t(:PendingOrdersDecline), orders_decline_path(:orderid => order.id), data: { confirm: t(:DeleteMsg) } %></td>
      </tr>


  <% end %>
</table>
  <%= will_paginate %>
</div>

app/views/orders/show.html.erb
<h4></h4>
<!--
<div class="container">
  <div class="process">
    <div class="process-row">
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-user fa-3x"></i></button>
        <p>Personal data</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-default btn-circle" disabled="disabled"><i class="fa fa-usd fa-3x"></i></button>
        <p>Payment</p>
      </div>
      <div class="process-step">
        <button type="button" class="btn btn-success btn-circle" disabled="disabled"><i class="fa fa-thumbs-up fa-3x"></i></button>
        <p>Confirmation</p>
      </div>
    </div>
  </div>-->

  <!-- Full Width Image Header with Logo -->
<!-- Image backgrounds are set within the full-width-pics.css file. -->
<div class="row">
<div class="col-lg-12">
  <h3>
  <% if(!session[:admin]) %>
   <div class="alert alert-success" role="alert">
    <strong><span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>

      <%=t :OrderConfirmationMessage %></strong>
  </div>
  <% end %>

  <% if(session[:admin]) %>
        <div class="alert alert-info" role="alert">
          <strong><span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
            <%=t :OrderCustomerReviewMsg %></strong>
        </div>
    <% end %>
  </h3>
  </div>
</div>

<!-- Content Section -->

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="section-heading"><%=t :OrderConfirmationMenu %></h1>
        <p class="lead section-lead">
        <table class="table table-striped">
          <tr>
            <td><%=t :OrderName %>:</td>
            <td><%= @menu.name %></td>
          </tr>
          <tr>
            <td><%=t :OrderChefName %>:</td>
            <td><%= @menu.chef.name %></td>
          </tr>
          <tr>
            <td><%=t :OrderNoOfGuests %>:</td>
            <td><%= @order.no_of_guests %></td>
          </tr>
          <tr>
            <td><%=t :OrderMenuPrice %>:</td>
            <td><%=@order.currency%> <%= @menu.price %></td>
          </tr>
          <tr>
            <td><%=t :OrderNetPrice %>:</td>
            <td><%=@order.currency%> <%= @order.net_price %></td>
          </tr>
          <tr>
            <td><%=t :OrderCookDate %>:</td>
            <td><%=@order.cook_date%></td>
          </tr>
        </table>
        </p>
      </div>
    </div>


    <!-- /.row -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="section-heading"><%=t :OrderConfirmationAddressBilling %></h1>
        <p class="lead section-lead">
        <table class="table table-striped">
          <tr>
            <td><%=t :OrderName %></td>
            <td><%= @order.name %></td>
          </tr>
          <tr>
            <td><%=t :OrderEMail %></td>
            <td><%= @order.email %></td>
          </tr>
          <tr>
            <td><%=t :OrderPhone %></td>
            <td><%= @order.phone %></td>
          </tr>
          <tr>
            <td><%=t :OrderStreet %></td>
            <td><%= @order.street %></td>
          </tr>
          <tr>
            <td><%=t :OrderCity %></td>
            <td><%= @order.city %></td>
          </tr>
          <tr>
            <td><%=t :OrderPostalcode %></td>
            <td><%= @order.postalcode %></td>
          </tr>
          <tr>
            <td><%=t :OrderCountry %></td>
            <td><%= @order.country %></td>
          </tr>
        </table>
        </p>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->